### ISSUE TITLE
Product info is not valid - Amazon - error getting product currency

### ISSUE THREAD

**Issue by heya0** [Crinibus/scraper#207]
There is still the problem

ubuntu@VM-0-7-ubuntu:~/amazon/scraper-2.4.1$ python3 main.py -a -c arcteryx -u https://www.amazon.com/dp/B0B8MC7QVT
Adding product with category 'arcteryx' and url 'https://www.amazon.com/dp/B0B8MC7QVT'
Product info is not valid - category: 'arcteryx' - url: https://www.amazon.com/dp/B0B8MC7QVT

**Comment by Crinibus** [comment]
@heya0 Could I get you to try adding the same product from Amazon again but using the new branch ```fix-amazon-get-currency``` this time?

I think I have fixed the problem with getting the currency

**Comment by Crinibus** [comment]
I will close this, as I have tested getting currency from Amazon using a VPN to USA which I think the problem was before
