### ISSUE TITLE
sqlite3.IntegrityError: NOT NULL constraint failed: products.product_code

### ISSUE THREAD

**Issue by salmansarwar5102** [Crinibus/scraper#235]
i am not sure what exactly is the issue here but it has something to do with sql. ive pasted the entire error in the link.

https://paste.ofcode.org/diyMQ6d4aKV75gnTG8H9dA

**Comment by Crinibus** [comment]
Hi, I will check why this happens when I get the time

**Comment by Crinibus** [comment]
Can you please try to add your product with the [new released version (3.0.2)](https://github.com/Crinibus/scraper/releases/tag/v3.0.2)
