### ISSUE TITLE
Very good work! Possibility of adding other sites?

### ISSUE THREAD

**Issue by inznn** [Crinibus/scraper#247]
Hello, excellent job, how could I add other sites?

**Comment by Crinibus** [comment]
Hello, thank you for the kind words!

To add new sites to scrape from you can look into the scraper/domains.py file. There you can add a new class that inherits from the BaseWebsiteHandler class (see how the other classes are written). Then add the new class to the dictionary "SUPPORTED_DOMAINS". That should be it.
If you want to visualize the prices from the new site, then you can add a key with the site's name and a value with a HEX color to the dictionary "WEBSITE_COLORS" in the file scraper/constants.py.

Thank you for showing interest in this project!
