### ISSUE TITLE
No visualization is displayed

### ISSUE THREAD

**Issue by MixFix228** [Crinibus/scraper#253]
No visualization is displayed
![image](https://github.com/user-attachments/assets/9b190ec8-b5c5-4873-be5d-3fd396a69f09)

**Comment by Crinibus** [comment]
Hi, in the newest release (version 3.2.2) it will print a message if no products are found when visualizing or listing products.
Thank you for taking the time to report this issue.

**Comment by MixFix228** [comment]
> Hi, in the newest release (version 3.2.2) it will print a message if no products are found when visualizing or listing products. Thank you for taking the time to report this issue.

![image](https://github.com/user-attachments/assets/769ad338-2934-47d5-b83b-395547f4ca73)

I installed the new version. and still nothing. maybe I'm doing something wrong? please help me solve the problem.

**Comment by Crinibus** [comment]
Where do you run the program? Are you in a desktop environment? If so, then one or more browser tabs should open and display the graphs of the products you have scraped.

**Comment by MixFix228** [comment]
> Where do you run the program? Are you in a desktop environment? If so, then one or more browser tabs should open and display the graphs of the products you have scraped.

OC Ubuntu 20
I thought the graph on the command line was shown after entering a command. Oh, I'm sorry.

**Comment by Crinibus** [comment]
No worries, the section about visualization could be more descriptive on how the graphs are shown
